name:                pine
version:             0.1.0.0
github:              "githubuser/pine"
license:             Zlib
author:              "Daniel Grinshpon"
maintainer:          "GrinshponDaniel@protonmail.com"
copyright:           "2019 Daniel Grinshpon"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis: Functional Reactive 2D Game Framework
category:            Game

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/pine#readme>

dependencies:
- base >= 4.7 && < 5
- sdl2 >= 2.4 && < 2.5
- sdl2-image >= 0.1 && < 2.1
- containers >= 0.6 && < 0.7
- text >= 1.2.3 && < 1.3
- stm >= 2.4 && < 2.6

library:
  source-dirs: src
  other-modules: []

executables:
  pine-exe:
    main:                Main.hs
    source-dirs:         app
    other-modules: []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pine

tests:
  pine-test:
    main:                Spec.hs
    source-dirs:         test
    other-modules: []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pine
